
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 02 14:56:10 ICT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 19;
  public static final int TRUELITERAL = 4;
  public static final int PERCENT = 21;
  public static final int SEMICOLON = 15;
  public static final int PLUS = 17;
  public static final int RPAREN = 12;
  public static final int RCURLY = 8;
  public static final int LPAREN = 11;
  public static final int RSQBRACKET = 10;
  public static final int COLON = 16;
  public static final int NULLLITERAL = 6;
  public static final int FALSELITERAL = 5;
  public static final int LSQBRACKET = 9;
  public static final int STRINGLITERAL = 3;
  public static final int LCURLY = 7;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int DIVIDE = 20;
  public static final int NUMBERLITERAL = 2;
  public static final int MINUS = 18;
  public static final int error = 1;
  public static final int ASSIGN = 14;
}

