
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 01 08:00:23 ICT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 27;
  public static final int TRUELITERAL = 12;
  public static final int PERCENT = 29;
  public static final int SEMICOLON = 23;
  public static final int ELSE = 5;
  public static final int PLUS = 25;
  public static final int RPAREN = 20;
  public static final int INT = 2;
  public static final int WHILE = 6;
  public static final int RCURLY = 16;
  public static final int RETURN = 8;
  public static final int IF = 4;
  public static final int COLON = 24;
  public static final int LPAREN = 19;
  public static final int RSQBRACKET = 18;
  public static final int NULLLITERAL = 14;
  public static final int LSQBRACKET = 17;
  public static final int FALSELITERAL = 13;
  public static final int ID = 9;
  public static final int STRINGLITERAL = 11;
  public static final int LCURLY = 15;
  public static final int COMMA = 21;
  public static final int EOF = 0;
  public static final int DIVIDE = 28;
  public static final int INTLITERAL = 10;
  public static final int MINUS = 26;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int FOR = 7;
  public static final int VOID = 3;
}

